redmine/plugins/lychee_custom_field/config/routes.rb
resources :custom_field_categories, only: %i[index new edit create update destroy]

resources :required_custom_fields, only: :index do
  collection do
    patch 'bulk_update'
  end
end

resources :invisible_custom_field_enumerations, only: :index do
  collection do
    patch 'bulk_update'
  end
end

resources :custom_field_setting_state, only: [:index]

delete 'custom_field_setting_state/required/:id/',
  to: 'custom_field_setting_state#required_bulk_update',
  as: 'required_bulk_update'

delete 'custom_field_setting_state/invisible/:source_id/:id/',
  to: 'custom_field_setting_state#invisible_bulk_update',
  as: 'invisible_bulk_update'

put 'projects/:project_id/per_project_lists/:custom_field_id',
    to: 'per_project_lists#update_all',
    as: 'update_all_per_project_list'
put 'projects/:project_id/per_project_lists/:custom_field_id/add',
    to: 'per_project_lists#add',
    as: 'add_possible_value'
delete 'projects/:project_id/per_project_lists/:custom_field_id/delete/:index/',
    to: 'per_project_lists#destroy',
    as: 'destroy_possible_value'

put 'projects/:project_id/per_project_kv/:custom_field_id',
    to: 'per_project_kv#update_all',
    as: 'update_all_per_project_kv'
put 'projects/:project_id/per_project_kv/:custom_field_id/add',
    to: 'per_project_kv#add',
    as: 'add_possible_enumeration'
delete 'projects/:project_id/per_project_kv/:custom_field_id/delete/:index/',
    to: 'per_project_kv#destroy',
    as: 'destroy_possible_enumeration'

# Per project REST api
get 'projects/:project_id/custom_fields',
    to: 'per_project_api#index',
    as: 'index_per_project'
get 'projects/:project_id/custom_fields/:custom_field_id',
    to: 'per_project_api#show',
    as: 'show_per_project'
post 'projects/:project_id/custom_fields/:custom_field_id',
    to: 'per_project_api#create',
    as: 'create_per_project'
delete 'projects/:project_id/custom_fields/:custom_field_id',
    to: 'per_project_api#delete',
    as: 'delete_per_project'
put 'projects/:project_id/custom_fields/:custom_field_id/position/:position',
    to: 'per_project_api#replace',
    as: 'replace_per_project_value'
put 'projects/:project_id/custom_fields/:custom_field_id',
    to: 'per_project_api#add',
    as: 'add_per_project_value'
delete 'projects/:project_id/custom_fields/:custom_field_id/position/:position',
    to: 'per_project_api#destroy',
    as: 'delete_per_project_value'

redmine/plugins/lychee_custom_field/app/views/custom_field_categories/_form.html.erb
<%= error_messages_for 'custom_field_category' %>

<div class="box tabular">
  <p><%= f.text_field :name, required: true %></p>

  <p>
    <%= label_tag t('label_custom_field') %>
    <span class="check_box_group">
      <%= collection_check_boxes(:custom_field_category, :custom_field_ids, @settable_custom_fields, :id, :name) do |b| %>
        <%= b.label { b.check_box + b.text } %>
      <% end %>
    </span>
  </p>
</div>

<%= f.submit %>

redmine/plugins/lychee_custom_field/app/views/custom_field_categories/edit.html.erb
<%= title [t(:label_custom_field_category_plural), custom_field_categories_path], @custom_field_category.name %>

<%= labelled_form_for @custom_field_category do |f| %>
  <%== render 'form', f: f %>
<% end %>

redmine/plugins/lychee_custom_field/app/views/custom_field_categories/index.html.erb
<div class="contextual">
  <%= link_to t(:label_custom_field_category_new), new_custom_field_category_path, class: 'icon icon-add' %>
</div>

<%= title t(:label_custom_field_category_plural) %>

<% if @custom_field_categories.present? %>
  <table class="list custom-field-categories">
    <thead>
      <tr>
        <th><%= t(:label_custom_field_category) %></th>
        <th><%= t(:label_custom_field_plural) %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @custom_field_categories.each do |custom_field_category| %>
        <tr class="<%= cycle 'odd', 'even' %>">
          <td class="name"><%= link_to custom_field_category.name, edit_custom_field_category_path(custom_field_category) %></td>
          <td class="custom-fields-count"><%= custom_field_category.custom_fields.count %></td>
          <td class="buttons">
            <%= reorder_handle_custom(custom_field_category, param: 'custom_field_category') %>
            <%= delete_link custom_field_category_path(custom_field_category) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="nodata"><%= t(:label_no_data) %></p>
<% end %>

<% html_title t(:label_custom_field_category_plural) %>

<% if Lychee::CustomFieldCategory.respond_to?(:acts_as_positioned) %>
  <%= javascript_tag do %>
    $(function() { $("table.custom-field-categories tbody").positionedItems(); });
  <% end %>
<% end %>

redmine/plugins/lychee_custom_field/app/views/custom_field_categories/new.html.erb
<%= title [t(:label_custom_field_category_plural), custom_field_categories_path], t(:label_custom_field_category_new) %>

<%= labelled_form_for @custom_field_category do |f| %>
  <%== render 'form', f: f %>
<% end %>