redmine/plugins/lac/config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

match 'issues/:id/associations',
      controller: 'association_chart',
      action: 'index',
      via: :get,
      as: 'issue_association_chart'

match 'lac/issues/:id/unrelated_issues',
      controller: 'lac_issues',
      action: 'unrelated_issues',
      via: %i[get post],
      as: 'lac_unrelated_issues'

get 'lac/issues/:id/data_for_editor',
    controller: 'association_chart',
    action: 'data_for_editor',
    as: 'lac_data_for_editor'

get 'lac/issues/:id/new',
    controller: 'lac_issues',
    action: 'new',
    as: 'lac_issue_new'

post 'lac/issues/:id/create',
     controller: 'lac_issues',
     action: 'create',
     as: 'lac_issue_create'

get 'lac/flash',
    controller: 'association_chart',
    action: 'flash_message',
    as: 'lac_flash_message'

redmine/plugins/lac/app/views/issues/_action_menu.html.erb
<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'lac', :plugin => 'lac' %>
<% end %>

<div class="contextual">
<%= link_to l(:button_edit), edit_issue_path(@issue), :onclick => 'showAndScrollTo("update", "issue_notes"); return false;', :class => 'icon icon-edit', :accesskey => accesskey(:edit) if @issue.editable? %>
<%= link_to l(:button_log_time), new_issue_time_entry_path(@issue), :class => 'icon icon-time-add' if User.current.allowed_to?(:log_time, @project) %>
<%= watcher_link(@issue, User.current) %>
<%= link_to l(:label_issue_association_chart), issue_association_chart_path(@issue), :class => 'icon icon-association-chart' if User.current.allowed_to?(:view_lac, @project) %>
<%= link_to l(:button_copy), project_copy_issue_path(@project, @issue), :class => 'icon icon-copy' if User.current.allowed_to?(:add_issues, @project) %>
<%= link_to l(:button_delete), issue_path(@issue), :data => {:confirm => issues_destroy_confirmation_message(@issue)}, :method => :delete, :class => 'icon icon-del' if User.current.allowed_to?(:delete_issues, @project) %>
</div>