redmine/plugins/lychee_time_management/config/routes.rb
# frozen_string_literal: true

namespace :lychee_time_management do
  namespace :api do
    namespace :v1 do
      resources :working_hours, only: %i[create], defaults: { format: 'json' }
    end
  end
end

get '/time_management', to: 'time_management#index', as: 'time_management_index'
get '/time_management/project_calendar', to: 'time_management#index', as: 'time_management_project_calendar'

namespace :lychee_time_management do
  resources :projects, only: %i[index show] do
    resource :issue_tree, only: :show
    resource :filter, only: :show
  end
  resources :issues, only: %i[index update] do
    get :mine, on: :collection, as: :my
    member do
      get :allowed_statuses
    end
  end
  resources :versions, only: %i[index]
  resources :activities, only: %i[index]
  resources :indirect_activities, only: %i[index]
  resources :work_plans do
    post 'derive_from_issues', on: :collection
    post 'derive_from_group_issues', on: :collection
    get 'derivable_from_issues', on: :collection
  end
  resources :ltm_time_entries
  resources :principals, only: :index
  resources :attachments, only: %i[show create destroy]
end

namespace :table_mode do
  resources :time_entries, only: %i[index create update destroy]
  resources :custom_fields, only: :index
  resources :project_filters, only: :index
  resources :projects, only: :index do
    get :inherit, on: :collection
  end
  resources :filters, only: :index
  resources :issues, only: :index
  resources :activities, only: :index
end

resource :ltm_google_calendar_syncs, only: %i[edit destroy] do
  collection do
    get 'initiate_oauth_flow'
    get 'callback'
  end
end

redmine/plugins/lychee_time_management/app/views/lychee_time_management/hooks/_view_my_account_preferences.erb
<% calendar_sync = User.current.ltm_google_calendar_sync %>

<% if calendar_sync %>
  <div id="ltm_user_preferences" data-load-url="<%= edit_ltm_google_calendar_syncs_path %>">
    <p>
      <label><%= t(:label_ltm_google_account_connection) %></label>
    </p>
    <p>
      <label><%= t(:label_ltm_connected_google_calendar) %></label>
    </p>
  </div>
  <%= lychee_time_management_javascript_include_tag 'my_account_preferences' %>
<% else %>
  <p>
    <label><%= t(:label_ltm_google_account_connection) %></label>
    <%= link_to t(:label_connect_ltm_with_google_account), initiate_oauth_flow_ltm_google_calendar_syncs_path %>
  </p>
<% end %>

redmine/plugins/lychee_time_management/app/views/lychee_time_management/hooks/_view_settings_general_form.html.erb
<% unless LycheeTimeManagement::Settings.table_mode? %>
<div id="plugin_lychee_time_management_settings">
  <%= label_tag 'settings[plugin_lychee_time_management][issues_limit]', t(:label_ltm_issues_limit) %>
  <%= text_field_tag 'settings[plugin_lychee_time_management][issues_limit]', LycheeTimeManagement::Settings.issues_limit, size: 6 %>
  <%=
    # 上書きされるのはSettings.plugin_lychee_time_management全体なので、ここに出ないフィールドの値も含めないといけない
    lychee_time_management_settings_hidden_fields(LycheeTimeManagement::Settings.all.except(:issues_limit), "settings[plugin_lychee_time_management]")
  %>
</div>

<script type="text/javascript">
$(function(){
  var $gannt_items_limit_field = $('#settings_gantt_items_limit').parent();
  var $lychee_time_management_issues_limit_field = $('#plugin_lychee_time_management_settings');

  $gannt_items_limit_field.after($('<p>').html($lychee_time_management_issues_limit_field.children()));
  $lychee_time_management_issues_limit_field.remove();
});
</script>
<% end %>