redmine/plugins/lychee_project_report/config/routes.rb
# frozen_string_literal: true

resources :project_reports, controller: :project_report_overview, only: %i[index] do
  collection do
    resources :queries,
              only: %i[new edit create update destroy],
              controller: :project_report_queries,
              as: :project_report_queries do
      get :validates, on: :collection
    end

    resources :comments, controller: :project_report_comments, only: %i[show update], as: :project_report_comments

    resources :layouts, controller: :project_report_layouts, only: %i[update destroy], as: :project_report_layouts do
      resources :panels, controller: :lychee_project_report_panels, only: %i[index create show update destroy]

      post :create_shared_layout, to: 'project_report_shared_layouts#create'
    end

    resources :shared_layouts, controller: :project_report_shared_layouts, only: %i[update destroy], as: :project_report_shared_layouts
    resources :active_shared_layouts,
              controller: :project_report_active_shared_layouts,
              only: %i[index],
              as: :project_report_active_shared_layouts
    patch :active_shared_layouts, to: 'project_report_active_shared_layouts#bulk_update', as: :update_active_shared_layouts
  end

  resources :layouts, controller: :project_report_layouts, only: %i[create]

  resources :shared_layouts, only: %i[] do
    resources :panels, controller: :lychee_project_report_panels, only: %i[index create show update destroy]
  end
end

resource :project_report_setting, only: [:edit] do
  collection do
    patch :bulk_update
  end
end

resources :enabled_report_indice_settings, only: %i[index create update destroy]

resources :indice_settings do
  collection do
    get :calculate_module
    get :indice_type
    get :filter_item
    get :filter_value
  end
end

namespace :lychee_project_report do
  resources :projects, only: [:update] do
    resources :issues, only: [] do
      get :render, action: :render_html, on: :collection
    end
  end
end

resources :projects, only: [] do
  namespace :project_reports do
    resources :histories, only: %i[index]
  end

  resources :project_reports, only: %i[index show update], param: :date
  resource :project_report, only: %i[show], as: :current_report do
    member do
      post :reculculate
      get :operation_finished
    end
  end

  resources :versions, only: [] do
    resources :project_reports, only: %i[index show update], param: :date
    resource :project_report, only: %i[show], controller: :project_reports, as: :current_report do
      member do
        post :reculculate
        get :operation_finished
      end
    end
  end
end

patch 'lychee_project_report/settings', to: 'lychee_project_report/settings#update'

redmine/plugins/lychee_project_report/app/views/old_layout/_about.html.erb
<h2><%= l(:label_overview) -%></h2>
<div class="columnbox table">
  <table>
    <tbody>
      <tr>
        <td><%= l(:field_project) -%></td>
        <% start_date = project.term.try(:start_date) %>
        <% end_date = project.term.try(:end_date) %>
        <td><%= "#{project.name} (#{show_reporting_date start_date} 〜 #{show_reporting_date end_date})" %></td>
      </tr>
      <% if version %>
      <tr>
        <td><%= l(:field_version) -%></td>
        <td><%= "#{version.name} (#{show_reporting_date version.start_date} 〜 #{show_reporting_date version.effective_date})" %></td>
      </tr>
      <% end %>
      <% if pending %>
        <tr>
          <td><%= l(:field_reporting_label_cwday) -%></td>
          <td><%= I18n.t('field_reporting_weekday', cwday: day_name(project.reporting_cwday)) %></td>
        </tr>
      <% else %>
        <tr>
          <td><%= l(:field_reporting_label_date) -%></td>
          <td><%= I18n.l reported_on %></td>
        </tr>
      <% end %>
      <tr>
        <td><%= l(:field_reporting_label_last) -%></td>
        <td>
          <% if last_reported_on.present? %>
            <%= I18n.l last_reported_on %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

redmine/plugins/lychee_project_report/app/views/old_layout/_comment.html.erb
<h2><%= t("label_project_report_comment") %></h2>
<% if User.current.project_report_managable?(project, true) %>
  <span class="symbol edit"></span>
<% end %>
<div class="columnbox">
  <p class="comment"><%= periodic_report_row.comment_text %></p>
</div>
<span class="ajax-path"
  data-show-path="<%= project_report_comment_path(periodic_report_row.project_report_comment) %>"
  data-update-path="<%= project_report_comment_path(periodic_report_row.project_report_comment) %>"
/>

redmine/plugins/lychee_project_report/app/views/old_layout/_report.html.erb
<div class="column">
  <h2>
    <%= periodic_report.try!(:indice_setting_name) %>
  </h2>
  <% if periodic_report.persisted? %>
    <% if User.current.project_report_managable?(project, true) %>
      <span class="symbol edit"></span>
    <% end %>
    <div class="columnbox">
      <h3><%= curled_box(periodic_report.decision) %>
        &nbsp;
        <%= periodic_report.indice_setting_name %>
        &nbsp;：&nbsp;
        <% if periodic_report.result.present? %>
          <span class="input"><%= report_result_value(periodic_report.result, periodic_report.unit_string) %></span>
        <% end %>
        <% result_from_prev = periodic_report.result_from_prev %>
        <% if result_from_prev.present? %>
          <span class="before">
            <%= rate_symbol_with_diff(result_from_prev) %>
            <%= report_result_value(result_from_prev.to_f.abs, periodic_report.unit_string) %>
          </span>
        <% end %>
      </h3>
      <p class="comment"><%= periodic_report.comment_text %></p>
    </div>
    <span class="ajax-path"
      data-show-path="<%= project_report_comment_path(periodic_report.project_report_comment) %>"
      data-update-path="<%= project_report_comment_path(periodic_report.project_report_comment) %>"
    />
  <% end %>
</div>